name: CI

on:
  push:
    branches:
      - source
  issues:
    types:
      [
        opened,
        closed,
        edited,
        milestoned,
        labeled,
        unlabeled,
        reopened,
        demilestoned,
      ]

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: latest
  
      - name: Download Issue
        uses: actions/github-script@v5
        id: download-issue
        with:
          script: |
            const script = require('./.github/scripts/download.cjs')
            await script({github, context, core, exec, issue: toJSON(github.event.issue)})
          # echo "Issue title: ${{ github.event.issue.title }}"
          # echo "Issue body: ${{ github.event.issue.body }}"
