name: CI

on:
  push:
    branches:
      - source
  issues:
    types:
      [
        opened,
        # closed,
        edited,
        milestoned,
        labeled,
        unlabeled,
        reopened,
        demilestoned,
      ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
  
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Issue Title
        id: check-issue-title
        run: |
          if [[ "${{ github.event.issue.title }}" != "[link]*" ]]; then
            echo "The issue title does not start with [link]. Exiting workflow."
            exit 0
          fi

      - name: Download Issue
        uses: actions/github-script@v5
        id: download-issue
        with:
          github-token: 1
          script: |
            const issue = ${{toJSON(github.event.issue)}}

            const script = require('./.github/scripts/save-markdown.cjs')
            await script({github, context, core, exec, issue: ${{toJSON(github.event.issue)}} }, 'src/content/post')

  
      - name: Update markdown file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: 'src/content/post/*.md'
          commit_message: 'Update issue file'
