name: CI

on:
  push:
    branches:
      - source
  issues:
    types:
      [
        opened,
        closed,
        edited,
        milestoned,
        labeled,
        unlabeled,
        reopened,
        demilestoned,
      ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Download Issue
        run: |
            const script = require('./.github/scripts/download.cjs')
            await script({github, context, core, exec})
          # echo "Issue title: ${{ github.event.issue.title }}"
          # echo "Issue body: ${{ github.event.issue.body }}"
